"""convert_services_to_association_models_with_quantity

Revision ID: 034e7c49a340
Revises: c2e0dff5878b
Create Date: 2026-01-06 13:32:40.976612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034e7c49a340'
down_revision = 'c2e0dff5878b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_main_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('appointment_main_services', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
