"""add electronic referral models

Revision ID: 061c2d513714
Revises: 5ac8a2fb837c
Create Date: 2026-01-20 22:34:12.748166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061c2d513714'
down_revision = '5ac8a2fb837c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electronic_referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('form_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_teeth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('tooth_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['electronic_referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_teeth')
    op.drop_table('electronic_referrals')
    # ### end Alembic commands ###
