"""Add is_child to Appointment

Revision ID: 1128f85b5923
Revises: 32c02b55749d
Create Date: 2025-12-22 20:44:52.582416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1128f85b5923'
down_revision = '32c02b55749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_child', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('is_child')

    # ### end Alembic commands ###
