"""replace center_id with clinic_id in appointments

Revision ID: 1d34589504e1
Revises: f270886d909a
Create Date: 2025-12-22 16:32:46.843902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d34589504e1'
down_revision = 'f270886d909a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('appointments_center_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['id'])
        batch_op.drop_column('center_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointments_center_id_fkey'), 'locations', ['center_id'], ['id'])
        batch_op.drop_column('clinic_id')

    # ### end Alembic commands ###
