"""add payment_method_id to appointments

Revision ID: 20e3ee048801
Revises: 3236a1cf891f
Create Date: 2025-12-22 17:29:32.909095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e3ee048801'
down_revision = '3236a1cf891f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'payment_methods', ['payment_method_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_method_id')

    # ### end Alembic commands ###
