"""Add pdf_filename to MedicalCertificate

Revision ID: 217032cb7c73
Revises: 061c2d513714
Create Date: 2026-01-21 10:42:45.452789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217032cb7c73'
down_revision = '061c2d513714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_certificates', schema=None) as batch_op:
        batch_op.drop_column('pdf_filename')

    # ### end Alembic commands ###
