"""add color to locations

Revision ID: 2cf1bde9fa7d
Revises: 7b9d0e1f2a34
Create Date: 2026-01-05 20:41:06.623960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf1bde9fa7d'
down_revision = '7b9d0e1f2a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('patient_phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('patient_phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
