"""add bonus_type to doctors

Revision ID: 2fe36eb01b8b
Revises: d27b93c8cde7
Create Date: 2026-01-11 23:51:46.884269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe36eb01b8b'
down_revision = 'd27b93c8cde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cashless', sa.Boolean(), nullable=True))

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('bonus_type')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('is_cashless')

    # ### end Alembic commands ###
