"""add additional service prices

Revision ID: 306dc0a3cce2
Revises: bc22cac4ba98
Create Date: 2025-12-22 15:42:21.334811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306dc0a3cce2'
down_revision = 'bc22cac4ba98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_service_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('additional_service_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['additional_service_id'], ['additional_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('additional_service_prices')
    # ### end Alembic commands ###
