"""Add additional_service_quantity to appointments

Revision ID: 32c02b55749d
Revises: 789b2cf946d8
Create Date: 2025-12-22 19:48:02.055122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c02b55749d'
down_revision = '789b2cf946d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_service_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('additional_service_quantity')

    # ### end Alembic commands ###
