"""Add lab_tech to appointments

Revision ID: 364827e04e86
Revises: 1128f85b5923
Create Date: 2025-12-22 23:18:47.360724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364827e04e86'
down_revision = '1128f85b5923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_tech', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('lab_tech')

    # ### end Alembic commands ###
