"""add center_id to users

Revision ID: 489439922110
Revises: 364827e04e86
Create Date: 2025-12-23 12:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489439922110'
down_revision = '364827e04e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_center_id', 'locations', ['center_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_center_id', type_='foreignkey')
        batch_op.drop_column('center_id')

    # ### end Alembic commands ###
