"""add journal fields to appointment

Revision ID: 4c6eb00c9e2c
Revises: 6b8e7879fa6f
Create Date: 2025-12-22 10:49:05.919647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6eb00c9e2c'
down_revision = '6b8e7879fa6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_services',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('additional_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['additional_service_id'], ['additional_services.id'], ),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('appointment_id', 'additional_service_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('comment')
        batch_op.drop_column('discount')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('cost')
        batch_op.drop_column('quantity')
        batch_op.drop_column('contract_number')

    op.drop_table('appointment_services')
    # ### end Alembic commands ###
