"""Change GlobalSetting value to TEXT type

Revision ID: 640a85cd96eb
Revises: df56fdb76951
Create Date: 2026-01-15 20:44:30.663668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640a85cd96eb'
down_revision = 'df56fdb76951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
