"""move manager to doctor and add doctor_id to appointments

Revision ID: 789b2cf946d8
Revises: fab19517f566
Create Date: 2025-12-22 18:13:03.957451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789b2cf946d8'
down_revision = 'fab19517f566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('doctor',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('manager')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('manager')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('doctor',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
