"""Add SystemMetrics model for monitoring

Revision ID: 8867ebace5af
Revises: 2fe36eb01b8b
Create Date: 2026-01-15 19:25:47.354756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8867ebace5af'
down_revision = '2fe36eb01b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('disk_total_gb', sa.Float(), nullable=False),
    sa.Column('disk_used_gb', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=True),
    sa.Column('appointments_count', sa.Integer(), nullable=True),
    sa.Column('journal_entries_count', sa.Integer(), nullable=True),
    sa.Column('doctors_count', sa.Integer(), nullable=True),
    sa.Column('clinics_count', sa.Integer(), nullable=True),
    sa.Column('organizations_count', sa.Integer(), nullable=True),
    sa.Column('services_count', sa.Integer(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('ram_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metrics_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metrics_timestamp'))

    op.drop_table('system_metrics')
    # ### end Alembic commands ###
