"""add clinic to doctor

Revision ID: 968327a0d9fe
Revises: 029c89f689ff
Create Date: 2025-12-21 13:10:52.712287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968327a0d9fe'
down_revision = '029c89f689ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['clinic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('clinic_id')

    # ### end Alembic commands ###
