"""add phone and manager to locations

Revision ID: cf0db7a40f78
Revises: 306dc0a3cce2
Create Date: 2025-12-22 15:53:56.557907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0db7a40f78'
down_revision = '306dc0a3cce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('manager', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('manager')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
