"""Add MedicalCertificate model

Revision ID: df56fdb76951
Revises: 8867ebace5af
Create Date: 2026-01-15 20:03:44.380665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df56fdb76951'
down_revision = '8867ebace5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('doc_series', sa.String(length=20), nullable=True),
    sa.Column('doc_number', sa.String(length=20), nullable=True),
    sa.Column('doc_issue_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_certificates_generated_at'), ['generated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_certificates_generated_at'))

    op.drop_table('medical_certificates')
    # ### end Alembic commands ###
