"""add center_id to appointments

Revision ID: fab19517f566
Revises: 20e3ee048801
Create Date: 2025-12-22 18:02:39.038951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab19517f566'
down_revision = '20e3ee048801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['center_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('center_id')

    # ### end Alembic commands ###
